import React, { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Calendar, Check, CheckCircle2, Clock, FileText, MessageCircle, Plus, Send, Stethoscope, User, X } from "lucide-react";
import logo from "../assets/myvita-logo-transparent.png";
import "../../src/styles.css";

const SPECIALTIES=["Clínica Geral","Cardiologia","Dermatologia","Ortopedia","Ginecologia","Pediatria"];
const seed={clinicName:"Clínica Bem-Estar",patients:[
{id:"p1",name:"Maria Silva",birthDate:"1987-04-12",appointments:[{id:"a1",specialty:"Clínica Geral",doctor:"Dr. Rui Mendes",date:"2026-08-28",time:"10:30"}],requests:[],results:[{id:"r1",title:"Análises ao sangue",date:"2026-08-10",summary:"Valores dentro da normalidade. Colesterol ligeiramente elevado.",seen:false}],messages:[{id:"m1",from:"clinic",text:"Olá Maria, os resultados das análises já estão disponíveis.",date:"2026-08-11"}]},
{id:"p2",name:"João Costa",birthDate:"1979-11-02",appointments:[],requests:[{id:"req1",specialty:"Cardiologia",preferredDate:"2026-09-02",reason:"Dores no peito ocasionais",status:"pending"}],results:[],messages:[]},
{id:"p3",name:"Ana Pereira",birthDate:"1995-06-23",appointments:[{id:"a2",specialty:"Dermatologia",doctor:"Dra. Sofia Nunes",date:"2026-09-05",time:"15:00"}],requests:[],results:[{id:"r2",title:"Exame de pele",date:"2026-08-15",summary:"Sem sinais de preocupação. Repetir controlo em 6 meses.",seen:true}],messages:[]}]};

const date=x=>new Date(x+"T00:00:00").toLocaleDateString("pt-PT",{day:"2-digit",month:"short",year:"numeric"});
function AppShell({title,subtitle,nav,tab,setTab,logout,children}){
 return <div className="proto-root"><aside><Link className="proto-brand" to="/"><img src={logo} alt="MyVita"/><strong>MyVita</strong></Link><nav>{nav.map(n=><button key={n.key} className={tab===n.key?"active":""} onClick={()=>setTab(n.key)}>{React.createElement(n.icon,{size:16})}{n.label}{n.count?<span>{n.count}</span>:null}</button>)}</nav><button className="switch-btn" onClick={logout}><ArrowLeft size={15}/> Sair da demonstração</button></aside><main><div className="proto-header"><div><span className="demo-badge">PROTÓTIPO FUNCIONAL</span><h1>{title}</h1><p>{subtitle}</p></div><Link to="/" className="back-site">Voltar ao website <ArrowLeft size={15}/></Link></div>{children}</main></div>
}
function Login({patients,enter}){
 const [role,setRole]=useState("patient"),[pid,setPid]=useState(patients[0].id);
 return <div className="login-page"><div className="login-card"><div className="login-head"><span>DEMONSTRAÇÃO</span><h1>MyVita</h1><p>Marcações. Resultados. Mensagens. Sem telefonemas.</p></div><div className="login-body"><label>Entrar como</label><div className="role-row"><button className={role==="patient"?"active":""} onClick={()=>setRole("patient")}><User/>Paciente</button><button className={role==="clinic"?"active":""} onClick={()=>setRole("clinic")}><Stethoscope/>Clínica</button></div>{role==="patient"?<label>Paciente de demonstração<select value={pid} onChange={e=>setPid(e.target.value)}>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:<p className="demo-help">Vai entrar como equipa da <b>Clínica Bem-Estar</b>, com acesso aos dados fictícios da demonstração.</p>}<button className="btn btn-gold full" onClick={()=>enter(role,role==="patient"?pid:null)}>Entrar</button></div></div><p className="demo-disclaimer">Dados fictícios. Não são utilizados dados reais de saúde.</p></div>
}
function Patient({p,actions,logout}){
 const [tab,setTab]=useState("appointments"),[show,setShow]=useState(false),[form,setForm]=useState({specialty:SPECIALTIES[0],preferredDate:"",reason:""}),[msg,setMsg]=useState("");
 const send=()=>{if(form.preferredDate&&form.reason.trim()){actions.request(p.id,form);setForm({specialty:SPECIALTIES[0],preferredDate:"",reason:""});setShow(false)}};
 const sendMsg=()=>{if(msg.trim()){actions.message(p.id,"patient",msg);setMsg("")}};
 const nav=[{key:"appointments",label:"Consultas",icon:Calendar,count:p.requests.filter(r=>r.status==="pending").length},{key:"results",label:"Resultados",icon:FileText,count:p.results.filter(r=>!r.seen).length},{key:"messages",label:"Mensagens",icon:MessageCircle}];
 return <AppShell title={`Olá, ${p.name.split(" ")[0]}`} subtitle="O seu espaço pessoal na Clínica Bem-Estar" nav={nav} tab={tab} setTab={setTab} logout={logout}>
 {tab==="appointments"&&<div className="proto-card"><div className="card-title"><h2>Próximas consultas</h2><button className="btn btn-gold" onClick={()=>setShow(!show)}><Plus size={15}/>Pedir consulta</button></div>{show&&<div className="request-box"><label>Especialidade<select value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}>{SPECIALTIES.map(s=><option key={s}>{s}</option>)}</select></label><label>Data preferida<input type="date" value={form.preferredDate} onChange={e=>setForm({...form,preferredDate:e.target.value})}/></label><label>Motivo<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button className="btn btn-primary" onClick={send}>Enviar pedido</button></div>}{p.appointments.map(a=><div className="proto-row" key={a.id}><div><b>{a.specialty}</b><small>{a.doctor}</small></div><span className="badge success"><CheckCircle2 size={13}/>{date(a.date)} · {a.time}</span></div>)}{p.requests.map(r=><div className="proto-row" key={r.id}><div><b>{r.specialty}</b><small>{r.reason}</small></div><span className={`badge ${r.status==="pending"?"accent":"danger"}`}>{r.status==="pending"?"Pedido enviado":"Recusado"}</span></div>)}</div>}
 {tab==="results"&&<div className="proto-card"><div className="card-title"><h2>Resultados de exames</h2></div>{p.results.length?p.results.map(r=><button className="result-row" key={r.id} onClick={()=>actions.seen(p.id,r.id)}><div><b>{r.title}</b><small>{date(r.date)}</small><p>{r.summary}</p></div>{!r.seen&&<span className="badge accent">Novo</span>}</button>):<p className="empty">Ainda sem resultados.</p>}</div>}
 {tab==="messages"&&<Messages p={p} from="patient" msg={msg} setMsg={setMsg} send={sendMsg}/>}
 </AppShell>
}
function Messages({p,from,msg,setMsg,send}){
 return <div className="proto-card messages-card"><div className="card-title"><h2>Mensagens com a clínica</h2></div><div className="message-list">{p.messages.length?p.messages.map(m=><div className={`bubble ${m.from===from?"mine":""}`} key={m.id}>{m.text}<small>{date(m.date)}</small></div>):<p className="empty">Sem mensagens ainda.</p>}</div><div className="message-compose"><input placeholder="Escreva uma mensagem…" value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()}/><button className="btn btn-primary" onClick={send}><Send size={15}/></button></div></div>
}
function Clinic({patients,actions,logout}){
 const [tab,setTab]=useState("requests"),[pid,setPid]=useState(patients[0].id),[result,setResult]=useState({title:"",summary:""}),[msg,setMsg]=useState("");
 const p=patients.find(x=>x.id===pid); const pending=patients.flatMap(x=>x.requests.filter(r=>r.status==="pending").map(r=>({...r,patient:x})));
 const nav=[{key:"requests",label:"Pedidos",icon:Clock,count:pending.length},{key:"patients",label:"Pacientes",icon:User}];
 return <AppShell title="Clínica Bem-Estar" subtitle="Painel da equipa clínica" nav={nav} tab={tab} setTab={setTab} logout={logout}>
 {tab==="requests"&&<div className="proto-card"><div className="card-title"><h2>Pedidos de marcação</h2></div>{pending.map(r=><div className="proto-row" key={r.id}><div><b>{r.patient.name} · {r.specialty}</b><small>{r.reason}</small><small>Preferência: {date(r.preferredDate)}</small></div><div className="action-row"><button className="btn btn-danger" onClick={()=>actions.reject(r.patient.id,r.id)}><X size={14}/>Recusar</button><button className="btn btn-primary" onClick={()=>actions.approve(r.patient.id,r.id)}><Check size={14}/>Confirmar</button></div></div>)}</div>}
 {tab==="patients"&&<div className="clinic-patients"><div className="patient-list">{patients.map(x=><button className={pid===x.id?"active":""} onClick={()=>setPid(x.id)} key={x.id}><User size={15}/>{x.name}</button>)}</div><div className="patient-detail"><div className="proto-card"><h2>{p.name}</h2><small>Nascimento: {date(p.birthDate)}</small></div><div className="proto-card"><h3>Adicionar resultado</h3><input placeholder="Título" value={result.title} onChange={e=>setResult({...result,title:e.target.value})}/><textarea placeholder="Resumo para o paciente" value={result.summary} onChange={e=>setResult({...result,summary:e.target.value})}/><button className="btn btn-primary" onClick={()=>{if(result.title.trim()&&result.summary.trim()){actions.addResult(p.id,result);setResult({title:"",summary:""})}}}><Plus size={15}/>Publicar resultado</button></div><Messages p={p} from="clinic" msg={msg} setMsg={setMsg} send={()=>{if(msg.trim()){actions.message(p.id,"clinic",msg);setMsg("")}}}/></div></div>}
 </AppShell>
}
export default function Prototype(){
 const [data,setData]=useState(seed),[viewer,setViewer]=useState(null);
 const update=(id,fn)=>setData(d=>({...d,patients:d.patients.map(p=>p.id===id?fn(p):p)}));
 const actions={request:(id,f)=>update(id,p=>({...p,requests:[...p.requests,{...f,id:"req_"+Date.now(),status:"pending"}]})),approve:(id,rid)=>update(id,p=>{const r=p.requests.find(x=>x.id===rid);return {...p,requests:p.requests.filter(x=>x.id!==rid),appointments:[...p.appointments,{id:"a_"+Date.now(),specialty:r.specialty,doctor:"A atribuir",date:r.preferredDate,time:"A confirmar"}]}}),reject:(id,rid)=>update(id,p=>({...p,requests:p.requests.map(r=>r.id===rid?{...r,status:"rejected"}:r)})),seen:(id,rid)=>update(id,p=>({...p,results:p.results.map(r=>r.id===rid?{...r,seen:true}:r)})),addResult:(id,f)=>update(id,p=>({...p,results:[...p.results,{...f,id:"r_"+Date.now(),date:new Date().toISOString().slice(0,10),seen:false}]})),message:(id,from,text)=>update(id,p=>({...p,messages:[...p.messages,{id:"m_"+Date.now(),from,text,date:new Date().toISOString().slice(0,10)}]}))};
 if(!viewer)return <Login patients={data.patients} enter={(role,pid)=>setViewer({role,pid})}/>;
 return viewer.role==="patient"?<Patient p={data.patients.find(p=>p.id===viewer.pid)} actions={actions} logout={()=>setViewer(null)}/>:<Clinic patients={data.patients} actions={actions} logout={()=>setViewer(null)}/>;
}
