"""add audit_logs table

Revision ID: 76dad50950ee
Revises: 4d732e959e2f
Create Date: 2026-09-19 06:06:15.938900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76dad50950ee'
down_revision: str | None = '4d732e959e2f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('login_success', 'login_failure', 'logout', 'password_change', 'user_created', 'user_disabled', 'patient_created', 'patient_updated', 'patient_deleted', 'staff_created', 'staff_updated', 'appointment_created', 'appointment_updated', 'appointment_cancelled', 'clinic_created', 'permission_denied', 'csrf_failure', 'rate_limited', 'staff_viewed_patient', 'staff_viewed_appointment', 'patient_viewed_own_record', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'denied', name='audit_result'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_clinic_id', 'audit_logs', ['clinic_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_clinic_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
    # Postgres ENUM types created by op.create_table above are NOT dropped
    # by drop_table — without this, `downgrade` then `upgrade` again fails
    # with "type audit_action already exists".
    sa.Enum(name='audit_action').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_result').drop(op.get_bind(), checkfirst=True)
